### ISSUE TITLE
Intersect for Extent

### ISSUE THREAD

**Issue by felixcremer** [rafaqz/Extents.jl#11]
I am wondering, whether it would make sense to overload the intersect function for Extent types. I have two rasters that have slightly different Extents and I would like to quickly find the area of intersection for plotting purposes. 

I would expect that an intersect function would operate on the interval intersection of both dimensions after checking, that the dimension names are the same.

**Comment by rafaqz** [comment]
`Extents.intersection` should be what you want

**Comment by felixcremer** [comment]
Yes, thanks, that is exactly what I want. Sorry for the noise.
