### ISSUE TITLE
`Extents.intersect` is still exported in v 0.1.2

### ISSUE THREAD

**Issue by alex-s-gardner** [rafaqz/Extents.jl#18]
I'm not sure why by it looks like `Extents` inherits `intersect` from Base

**Comment by alex-s-gardner** [comment]
This caused an issue with MapTile where Extents.intersect() returned an empty Any() when Extents what upgraded from 0.1.1 to 0.1.2

**Comment by rafaqz** [comment]
Its a mistake that the depricated method was deleted in a minor release, I'll return it

**Comment by rafaqz** [comment]
Actually what youre seeing is just any base method works like that.

**Comment by alex-s-gardner** [comment]
That seems a bit strange. I all of Base explicitly added to Extents? I don't see this behavior with other packages

**Comment by rafaqz** [comment]
Yeah I should not guess from my phone wothout the code... it will be like that if you explicity using/import a base method or module, which I assumed we had somehow. But no.

There is actually a typoed `inersect` deprecation which is kind of hilarious and maybe what you mean? I cant see how you get interect

**Comment by rafaqz** [comment]
```julia
julia> using Revise

julia> Revise.intersect
intersect (generic function with 23 methods)
```

**Comment by rafaqz** [comment]
Finally solved this mystery - what you are seeing is that you get _autocompletion_ for `intersect` with Extents.jl because it has both `intersection` and `intersects`. All packages have the base methods, but Extents will accidentally autocomplete it.

You get the same behaviour with GeoInterface as it also has both of those methods

**Comment by alex-s-gardner** [comment]
Oh man.. that's a tough one to track down. 

It seems strange that all base methods are added to packages and can be accessed as `Pkg.method`... It seems like it would have been safer to only have methods introduced by the Package accessed this way.  But I'm sure there is a good reason that came with this compromise.
