### ISSUE TITLE
Forward `propertynames` to bounds

### ISSUE THREAD

**Issue by felixcremer** [rafaqz/Extents.jl#25]
I am not sure whether this is intentional, because we only want to have access to the dimensions separately but accessing the bounds key of an extent is throwing an error. 
This is especially confusing because it tab completes only to ext.bounds and not the separate dimensions to then error. 

```julia
julia> ext = Extent(X=(1,2),Y=(0,4))
Extent(X = (1, 2), Y = (0, 4))

julia> ext.bounds
ERROR: Extent has no field bounds
Stacktrace:
 [1] getproperty(ext::Extent{(:X, :Y), Tuple{Tuple{Int64, Int64}, Tuple{Int64, Int64}}}, key::Symbol)
   @ Extents ~/.julia/packages/Extents/LzSHL/src/Extents.jl:53
 [2] top-level scope
   @ REPL[45]:1
```

**Comment by rafaqz** [comment]
Ah maybe `propertynames` or some other method is missing?

**Comment by rafaqz** [comment]
I think bounds will need to use `getfield` manually

**Comment by rafaqz** [comment]
So we just need to forward `propertynames`
