### ISSUE TITLE
Feature request: methods to grow and shrink extents

### ISSUE THREAD

**Issue by asinghvi17** [rafaqz/Extents.jl#32]
It would be great to get `grow_extent(ext, 1)` or `grow_extent(ext, (1, 2))` or `grow_extent(ext, (X = 1, Y = 2))` as a way to "buffer" extents.

**Comment by rafaqz** [comment]
How about `Extents.resize(ext, 1)` then it can be negative. 

`Extents.resize(ext, X=1)` can also work as a keyword
