### ISSUE TITLE
Should Extents be moved to JuliaGeo?

### ISSUE THREAD

**Issue by alex-s-gardner** [rafaqz/Extents.jl#8]
Thinking about package development and standardization I'm wondering if Extents.jl should be moved to JuliaGeo?

**Comment by alex-s-gardner** [comment]
OK, that makes sense. Thanks for the explanation.

**Comment by rafaqz** [comment]
No worries, its a good question.

I would like it to be in an org some day too but Im not sure putting general things in julia geo is good for getting users and contributors from other fields.
